#!/bin/bash
app="$1"
stack="$2"
session_name="$ssh_$app-$stack"

tmux new-session -d -s $session_name
tmux select-window -t ${session_name}:0
for ip in `aws ec2 --profile st-preprod describe-instances --filters "Name=tag:app,Values=$app" "Name=tag:stack,Values=$stack*" "Name=instance-state-name,Values=running" | grep -i "PrivateIp.*," | awk '{ print $2 }' | cut -d',' -f1| sed -e 's/"//g'`
do
    tmux select-layout even-vertical
    tmux send-keys "ssh $ip" 'C-m'
    tmux split-window -v
done;
tmux send-keys 'exit' 'C-m'
tmux set synchronize-panes
tmux attach -t $session_name
